POST http://localhost:3000/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "primeiro video",
    "duration": 180
}

// Essas cerquilhas separam as requisições
###
GET http://localhost:3000/videos?search=node

###

PUT http://localhost:3000/videos/727b1165-7024-436f-be6e-c3de69e8ba51
Content-type: application/json

{
    "title": "Video 2",
    "description": "primeiro dasdsa",
    "duration": 180
}

###
DELETE http://localhost:3000/videos/727b1165-7024-436f-be6e-c3de69e8ba51